[build]
  command = "pnpm install --no-frozen-lockfile && pnpm --filter @repo/ui build && pnpm --filter blog build"
  publish = "apps/blog/build/client"
  functions = "apps/blog/build/server/netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  PNPM_FLAGS = "--no-frozen-lockfile"

[functions]
  node_bundler = "esbuild"

[build.processing]
  skip_processing = true


