[build]
  command = "pnpm --filter @repo/ui build && pnpm --filter blog build"
  publish = "apps/blog/build/client"
  functions = "apps/blog/build/server/netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/remix-adapter"

[build.processing]
  skip_processing = true


